stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python python-pip
    # - pip install --user -r requirements.txt # somehow this doesn't work
    - pip install Flask flask-cors pytest
    - pytest
